#sudo: false  #### cannot be enabled due to tor installation
language: java
jdk:
#  - oraclejdk7
  - oraclejdk8

before_install:
  - "sudo apt-get install -y tor"

before_deploy:
  - export RELEASE_PKG_FILES=$(ls ./assembly/target/spookystuff-assembly-*.zip)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: s3
  file_glob: true
  file: "${RELEASE_PKG_FILES}"
  access_key_id: "${AWSAccessKeyId}"
  secret_access_key: "${AWSSecretKey}"
  bucket: "s3://spooky-bin/"
  skip_cleanup: true
  acl: public_read
  on:
    branch:
      - master
      - branch-*