#sudo: false  #### cannot be enabled due to tor installation
language: java
jdk:
#  - oraclejdk7
  - oraclejdk8

env:
  - SPARK_VERSION="1.3.1"
  - SPARK_VERSION="1.4.1" EXTRA="-Ppipeline"
  - SPARK_VERSION="1.5.1" EXTRA="-Ppipeline"

before_install:
  - "sudo apt-get install -y tor"

install:
  - mvn install -q -DskipTests=true -B -q -Pall-inclusive-examples -Pdist -Pspark-${SPARK_VERSION} ${EXTRA}

script:
  - mvn test -B -Pspark-${SPARK_VERSION} ${EXTRA}

before_deploy:
  - export RELEASE_PKG_FILES=$(ls ./assembly/target/spookystuff-assembly-*)
  - echo "deploying ${RELEASE_PKG_FILES} to S3 releases"

deploy:
  provider: s3
#  file_glob: true
#  file: "${RELEASE_PKG_FILES}"
  local-dir: assembly/target/scala-2.10
  upload-dir: spookystuff/spark-${SPARK_VERSION}-scala-2.10
  access_key_id: "${AWSAccessKeyId}"
  secret_access_key: "${AWSSecretKey}"
  bucket: "spooky-bin"
  skip_cleanup: true
  acl: public_read
  on:
    branch:
      - master
      - branch-*
      - release-*