#sudo: false  #### cannot be enabled due to tor installation
language: java
jdk:
#  - oraclejdk7
  - oraclejdk8

env:
  - SPARK_BIN_VERSION=1.3
  - SPARK_BIN_VERSION=1.4

before_install:
  - "sudo apt-get install -y tor"

install:
  - mvn clean
  - mvn install -q -Pall-inclusive-examples -Pdist -Pspark-${SPARK_BIN_VERSION}

before_deploy:
  - export RELEASE_PKG_FILES=$(ls ./assembly/target/spookystuff-assembly-*)
  - echo "deploying ${RELEASE_PKG_FILES} to GitHub releases"

deploy:
  provider: s3
#  file_glob: true
#  file: "${RELEASE_PKG_FILES}"
  local-dir: assembly/target
  access_key_id: "${AWSAccessKeyId}"
  secret_access_key: "${AWSSecretKey}"
  bucket: "spooky-bin"
  skip_cleanup: true
#  acl: public_read
  on:
    branch:
      - master
      - branch-*