language: java
jdk:
#  - oraclejdk7
  - oraclejdk8

before_install:
  - "sudo apt-get install -y tor"

before_deploy:
  - export RELEASE_PKG_FILES=$(ls ./assembly/target/spookystuff-assembly-*.zip)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  provider: releases
  file_glob: true
  file: "${RELEASE_PKG_FILES}"
  skip_cleanup: true
  on:
    branch:
      - master
      - branch-*